export default {
  products: [
    {
      _id: 1,
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: 2,
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 40,
      brand: "Nike",
      rating: 3.5,
      numReviews: 20,
    },
    {
      _id: 3,
      name: "Best Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 90,
      brand: "Nike",
      rating: 5,
      numReviews: 8,
    },
    {
      _id: 4,
      name: "Reg Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4,
      numReviews: 15,
    },
  ],
};
